---
- name: "Pull full node container, {{ handshake_full_nodes_docker_image }}"
  ansible.builtin.command: docker pull "{{ handshake_full_nodes_docker_image }}"
  notify:
    - Restart Full Node Container

- name: Update the server
  ansible.builtin.include_role:
    name: update_server
