---
- name: "Pull full node container, {{ handshake_full_nodes_docker_image }}"
  ansible.builtin.command: /usr/local/bin/container_needs_updating "{{ handshake_full_nodes_docker_image }}"
  register: result
  changed_when: result.rc == 2
  notify:
    - Restart Full Node Container

- name: Update the server
  ansible.builtin.include_role:
    name: update_server
