---
- name: Uodate packages database
  ansible.builtin.apt:
    update_cache: true

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify:
    - Reboot Server
