---
common_with_handshake_full_node: true

### Uncomment and change any of these to override the defaults
#
# handshake_simple_resolver_docker_image: jamesstevens/handshake-simple-resolver
# handshake_simple_resolver_memory_cap: 1g

### Require clients to use DNS cookies, normal clients are likely to do this, abuse traffic less so
# handshake_simple_resolver_require_dns_cookies: true

### Acts as a public resolver by default
# handshake_simple_resolver_with_public_access: true

### Use these as upper level resolver to refer queries to
# handshake_simple_resolver_parent_resolvers:
#   - 82.68.70.162
#   - 82.68.70.163

### List of subnet allowed to use this resolver, use "any" to mean anybody
# handshake_simple_resolver_allowed_subnets:
#     - 192.168.0.0/16
#     - 10.0.0.0/8
#     - 172.16.0.0/12
#     - 127.0.0.0/8
