---
# NOTE: `group_vars` apply to *ALL* hosts in the group, if this is not what you
# want, add a `vars:` clause to individual hosts.
#
# Uncomment the next line and change the name, if you want to use a different container

# handshake_full_node_docker_image: jamesstevens/handshake-full-node
# handshake_full_node_data_directory: /opt/data/handshake-full-node
# handshake_full_node_hsd_log_level: warning
# handshake_full_node_hsd_additional_params: "--no-sig0 --no-wallet"
#
# handshake_full_node_hsd_public_node: true
# handshake_full_node_dns_auth_public: false
# handshake_full_node_dns_recurse_public: false
# handshake_full_node_dns_both_public: false
#
# handshake_full_node_hsd_private_node: false
# handshake_full_node_dns_auth_private: false
# handshake_full_node_dns_recurse_private: false
# handshake_full_node_dns_both_private: true

# check any of the other "roles/*/defaults/main.yaml" files for other variables you might want to change
