---
#
# This install from https://docs.docker.com/engine/install/debian/
#
- name: Make docker sources file
  ansible.builtin.template:
    src: templates/debian.docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.sources
    owner: root
    group: root
    mode: '0644'
  notify:
    - Remove unwanted docker packages

- name: Rest of the docker install, common wuth Ubuntu
  ansible.builtin.include_role:
    name: docker
    tasks_from: common
