all:
  vars:
    ansible_connection: ssh
    ansible_user: james
    ansible_python_interpreter: python3

handshake_full_nodes:
  hosts:
    debian13-full:
      ansible_host: 192.168.1.210
    ubuntu24-full:
      ansible_host: 192.168.1.220

handshake_simple_resolver:
  hosts:
    debian13-simple:
      ansible_host: 192.168.1.210
      vars:
        common_with_handshake_full_node: true
    ubuntu24-simple:
      ansible_host: 192.168.1.220

handshake_mailserver:
  hosts:
    debian13-mail:
      ansible_host: 192.168.1.210
    ubuntu24-mail:
      ansible_host: 192.168.1.220

powerdns_primary:
  hosts:
    debian13-pdns:
      ansible_host: 192.168.1.210
    ubuntu24-pdns:
      ansible_host: 192.168.1.220
