---
- name: Install Handshake Simple Resolver
  hosts: handshake_simple_resolver
  become: true
  tasks:
  - name: Install Handshake Simple Resolver
    ansible.builtin.include_role:
      name: handshake_simple_resolver
      tasks_from: install
