---
- name: Install Handshake Full Nodes
  hosts: handshake_full_nodes
  become: true
  tasks:
  - name: Install Handshake Full Nodes
    ansible.builtin.include_role:
      name: handshake_full_node
      tasks_from: install

- name: Install Handshake Simple Resolver
  hosts: handshake_simple_resolver
  become: true
  tasks:
  - name: Install Handshake Simple Resolver
    ansible.builtin.include_role:
      name: handshake_simple_resolver
      tasks_from: install

- name: Install Handshake Mail Server
  hosts: handshake_mailserver
  become: true
  tasks:
  - name: Install Handshake Mail Server
    ansible.builtin.include_role:
      name: handshake_mailserver
      tasks_from: install
