---
- name: Upgrade Handshake Full Nodes
  hosts: handshake_full_nodes
  become: true
  tasks:
  - name: Upgrade Handshake Full Nodes
    ansible.builtin.include_role:
      name: handshake_full_node
      tasks_from: upgrade

- name: Upgrade Handshake Simple Resolver
  hosts: handshake_simple_resolver
  become: true
  tasks:
  - name: Upgrade Handshake Simple Resolver
    ansible.builtin.include_role:
      name: handshake_simple_resolver
      tasks_from: upgrade
