---
- name: Upgrade Handshake Full Nodes
  hosts: handshake_full_nodes
  become: true
  tasks:
  - name: Upgrade Handshake Full Nodes
    ansible.builtin.include_role:
      name: handshake_full_node
      tasks_from: upgrade
