---
- name: Upgrade Handshake Full Nodes
  hosts: handshake_full_nodes
  become: true
  tasks:
  - name: Upgrade Handshake Full Nodes
    ansible.builtin.include_role:
      name: handshake_full_node
      tasks_from: upgrade

- name: Upgrade Handshake Simple Resolver
  hosts: handshake_simple_resolver
  become: true
  tasks:
  - name: Upgrade Handshake Simple Resolver
    ansible.builtin.include_role:
      name: handshake_simple_resolver
      tasks_from: upgrade

- name: Upgrade Handshake Mail Server
  hosts: handshake_mailserver
  become: true
  tasks:
  - name: Upgrade Handshake Mail Server
    ansible.builtin.include_role:
      name: handshake_mailserver
      tasks_from: upgrade

- name: Upgrade PowerDNS Primary
  hosts: powerdns_primary
  become: true
  tasks:
  - name: Upgrade PowerDNS Primary
    ansible.builtin.include_role:
      name: powerdns_primary
      tasks_from: upgrade
